site_name: Evalica
site_author: Dmitry Ustalov
site_description: Evalica, your favourite evaluation suite.
copyright: Copyright &copy; 2024 Dmitry Ustalov
repo_name: dustalov/evalica
repo_url: https://github.com/dustalov/evalica
nav:
- Home: index.md
- Counting: counting.md
- Bradley-Terry: bradley-terry.md
- Elo: elo.md
- Linear Algebra: linalg.md
- Utilities: utils.md
- Errors: errors.md
- Migration: migration.md
theme:
  name: material
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        - https://pandas.pydata.org/docs/objects.inv
        options:
          show_root_heading: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
